11 created contract WalletDataSource and Modified UserDataSource && FileDataSource
IvanSolaDelgado/crypto-wallet pull request #16
Opened 2023-05-15 21:41 UTC by salinas116030

Resolves #14

2023-05-15 22:10 UTC, alvarolarraya12 requested changes
Yo almacenaría todos los DataSource en una misma carpeta llamada DataSources en vez de crear una carpeta para cada DataSource con solo un elemento

2023-05-16 10:43 UTC, alvarolarraya12 approved these changes

2023-05-16 11:08 UTC, IvanSolaDelgado requested changes
Por aquí te dejo los comments polucio :)

2023-05-16 11:08 UTC, IvanSolaDelgado commented on app/Infrastructure/Controllers/GetsWalletCryptocurrenciesController.php
> +        $wallet_id = intval($wallet_id);
Deberíamos seguir con camelCase (walletId)? Aunque en el JSON se llame así esta es nuestra variable creo que si deberíamos seguir con camelCase :)

2023-05-16 11:08 UTC, IvanSolaDelgado commented on app/Infrastructure/Persistence/FileWalletDataSource.php
> +    public function findById(string $userId): ?Wallet
Pregunta: Cuando queremos buscar una wallet le metemos como parámetro el userId como está aquí o le meteríamos la walletId?

2023-05-16 11:08 UTC, IvanSolaDelgado commented on app/Infrastructure/Persistence/FileWalletDataSource.php
> +        return new Wallet(0);
La Wallet tiene su walletId como int? No era un string igual que el userId?

2023-05-16 11:08 UTC, IvanSolaDelgado commented on tests/app/Infrastructure/Controller/GetsWalletCryptocurrenciesControllerTest.php
> +        $response = $this->get('api/wallet/-5');
Separar AAA entre la aserción y la ejecución del get :)

2023-05-16 11:09 UTC, merged